language: python

python:
  - "3.8"

before_install:
  - nvm install node

# command to install dependencies
install:
  - pip install -r requirements.txt

# SonarQube Analysis
addons:
  sonarcloud:
    organization: "johnbarton27" # the key of the org you chose at step #3

script:
  - coverage run --source=streamdeckx tests/run_tests.py
  - coverage xml
  - sonar-scanner
